int0:
    push dword 0
    call interrupt
    add esp, 4
    iret

int1:
    push dword 1
    call interrupt
    add esp, 4
    iret

int2:
    push dword 2
    call interrupt
    add esp, 4
    iret

int3:
    push dword 3
    call interrupt
    add esp, 4
    iret

int4:
    push dword 4
    call interrupt
    add esp, 4
    iret

int5:
    push dword 5
    call interrupt
    add esp, 4
    iret

int6:
    push dword 6
    call interrupt
    add esp, 4
    iret

int7:
    push dword 7
    call interrupt
    add esp, 4
    iret

int8:
    push dword 8
    call interrupt
    add esp, 4
    iret

int9:
    push dword 9
    call interrupt
    add esp, 4
    iret

int10:
    push dword 10
    call interrupt
    add esp, 4
    iret

int11:
    push dword 11
    call interrupt
    add esp, 4
    iret

int12:
    push dword 12
    call interrupt
    add esp, 4
    iret

int13:
    push dword 13
    call interrupt
    add esp, 4
    iret

int14:
    push dword 14
    call interrupt
    add esp, 4
    iret

int15:
    push dword 15
    call interrupt
    add esp, 4
    iret

int16:
    push dword 16
    call interrupt
    add esp, 4
    iret

int17:
    push dword 17
    call interrupt
    add esp, 4
    iret

int18:
    push dword 18
    call interrupt
    add esp, 4
    iret

int19:
    push dword 19
    call interrupt
    add esp, 4
    iret

int20:
    push dword 20
    call interrupt
    add esp, 4
    iret

int21:
    push dword 21
    call interrupt
    add esp, 4
    iret

int22:
    push dword 22
    call interrupt
    add esp, 4
    iret

int23:
    push dword 23
    call interrupt
    add esp, 4
    iret

int24:
    push dword 24
    call interrupt
    add esp, 4
    iret

int25:
    push dword 25
    call interrupt
    add esp, 4
    iret

int26:
    push dword 26
    call interrupt
    add esp, 4
    iret

int27:
    push dword 27
    call interrupt
    add esp, 4
    iret

int28:
    push dword 28
    call interrupt
    add esp, 4
    iret

int29:
    push dword 29
    call interrupt
    add esp, 4
    iret

int30:
    push dword 30
    call interrupt
    add esp, 4
    iret

int31:
    push dword 31
    call interrupt
    add esp, 4
    iret

int32:
    push dword 32
    call interrupt
    add esp, 4
    iret

int33:
    push dword 33
    call interrupt
    add esp, 4
    iret

int34:
    push dword 34
    call interrupt
    add esp, 4
    iret

int35:
    push dword 35
    call interrupt
    add esp, 4
    iret

int36:
    push dword 36
    call interrupt
    add esp, 4
    iret

int37:
    push dword 37
    call interrupt
    add esp, 4
    iret

int38:
    push dword 38
    call interrupt
    add esp, 4
    iret

int39:
    push dword 39
    call interrupt
    add esp, 4
    iret

int40:
    push dword 40
    call interrupt
    add esp, 4
    iret

int41:
    push dword 41
    call interrupt
    add esp, 4
    iret

int42:
    push dword 42
    call interrupt
    add esp, 4
    iret

int43:
    push dword 43
    call interrupt
    add esp, 4
    iret

int44:
    push dword 44
    call interrupt
    add esp, 4
    iret

int45:
    push dword 45
    call interrupt
    add esp, 4
    iret

int46:
    push dword 46
    call interrupt
    add esp, 4
    iret

int47:
    push dword 47
    call interrupt
    add esp, 4
    iret

int48:
    push dword 48
    call interrupt
    add esp, 4
    iret

int49:
    push dword 49
    call interrupt
    add esp, 4
    iret

int50:
    push dword 50
    call interrupt
    add esp, 4
    iret

int51:
    push dword 51
    call interrupt
    add esp, 4
    iret

int52:
    push dword 52
    call interrupt
    add esp, 4
    iret

int53:
    push dword 53
    call interrupt
    add esp, 4
    iret

int54:
    push dword 54
    call interrupt
    add esp, 4
    iret

int55:
    push dword 55
    call interrupt
    add esp, 4
    iret

int56:
    push dword 56
    call interrupt
    add esp, 4
    iret

int57:
    push dword 57
    call interrupt
    add esp, 4
    iret

int58:
    push dword 58
    call interrupt
    add esp, 4
    iret

int59:
    push dword 59
    call interrupt
    add esp, 4
    iret

int60:
    push dword 60
    call interrupt
    add esp, 4
    iret

int61:
    push dword 61
    call interrupt
    add esp, 4
    iret

int62:
    push dword 62
    call interrupt
    add esp, 4
    iret

int63:
    push dword 63
    call interrupt
    add esp, 4
    iret
